### PR TITLE
Enable multiple parses from one fetch

### PR DESCRIPTION
**Pull request by pmjones**
This PR adds the ability to return multiple parses from a single wikitext fetch. This cuts down on network traffic.  It additionally removes non-exceptional die() calls to return empty arrays, so as not to interrupt later parses.

### CODE REVIEW

**Comment by pmjones** [comment]
Thanks. :-) Expect more in the next couple days.

**Comment by ybourque** [comment]
No problem. Great work. If you don't mind, could you add more comments/change the ones that no longer apply in your next PR. I'll need to rewrite the documentation as the parser's functionality has changed quite a bit.

**Comment by pmjones** [comment]
Can do. I may make some significant style changes to bring the codebase into line with PSR-1 and PSR-2, if that doesn't bother you too much.

**Comment by ybourque** [comment]
TBH, I'd prefer if you kept style changes to a minimum, unless existing format and choices prevent you from adding functionality. Thanks.

**Pull request merged**
